### ISSUE TITLE
Add ImageStreams to keep Kaoto updated

### ISSUE THREAD

**Issue by Delawen** [KaotoIO/kaoto-operator#24]
The imageStream gets the `latest` tag updated. If we point the `Deployment` to this image stream instead of quay or docker, then Kaoto gets always updated with latest `nightly`, `latest`, `main`, or whatever we decide to.

```
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: kaoto-backend
  namespace: kaoto
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: kaotoio/backend:nightly
    importPolicy:
      scheduled: true
    name: nightly
    referencePolicy:
      type: Source
```
